### ISSUE TITLE
Bug in MySql Migration

### ISSUE THREAD

**Issue by P9os** [sunengine/SunEngine#35]
In 001-Initial migration with version 20190705000000 using key "FK_CategoryOperationAccesses_CategoryAccessId_CategoryAccesses_Id". This lenght key is 65 symbols. Max lenght key in MySql is 64.
Fragment code with this migrations.
`Create.Table("CategoryOperationAccesses".s())
                .WithColumn("CategoryAccessId".s()).AsInt32().PrimaryKey().NotNullable().Indexed()
                .ForeignKey("CategoryAccesses".s(), "Id".s())
                .WithColumn("OperationKeyId".s()).AsInt32().PrimaryKey().NotNullable().Indexed()
                .ForeignKey("OperationKeys".s(), "OperationKeyId".s())
                .WithColumn("Access".s()).AsBoolean().NotNullable();
`

**Comment by Dmitrij-Polyanin** [comment]
Made in my and dev brunch.

**Comment by Dmitrij-Polyanin** [comment]
No done in master
