### ISSUE TITLE
Front changes for security patch

### ISSUE THREAD

**Issue by kreuwont** [sunengine/SunEngine#44]
Need display relevant constraints after security patch on front-end.
@Dmitrij-Polyanin

**Comment by Dimitij-Polianin** [comment]
I did not understand. Can you explain more?

**Comment by DimitrOkeanij** [comment]
You mean to display to admin?

**Comment by kreuwont** [comment]
> You mean to display to admin?

Yes, u need show all server errors from this patch on admin panel

**Comment by DimitrOkeanij** [comment]
From logs?

**Comment by DimitrOkeanij** [comment]
I understand, you want security tracking if someone tries to hack site?

**Comment by DimitrOkeanij** [comment]
So need to show logs on admin panel.
1 type. All errors.
2 type. Security.
Good point to further Milestones.

**Comment by kreuwont** [comment]
On PR #46 I was add many new constraints on backend. Frontend havent correct alerts with message for this.

**Comment by DmitrijOkeanij** [comment]
For old time I close it. All messages  will be displayed as Server error, without personal message.
