### ISSUE TITLE
demo site not loading ?

### ISSUE THREAD

**Issue by geminigeek** [sunengine/SunEngine#48]
https://sunengine.site/

**Comment by DimitrOkeanij** [comment]
Yes. Domen expired. In proccess of transfer to other registrator.

**Comment by geminigeek** [comment]
hi, till the site is up , kindly add installation instruction somewhere, or point me where they are, thanks

**Comment by DimitrOkeanij** [comment]
I think in 0-3 days domain will renew, so all will work fine.
I activate temporary option, so use it for now:
https://95.216.139.72
And in any case you can write me on Telegram

**Comment by DimitrOkeanij** [comment]
![image](https://user-images.githubusercontent.com/10674646/72512748-4a6d1c00-385d-11ea-95ae-8407fbd561f0.png)

Only 19 January or after registrator will be changed. Not so quick as I think.

**Comment by DimitrOkeanij** [comment]
Domains moved to new registrator and sites now working.
https://sunengine.site
https://demo.sunengine.site
