### ISSUE TITLE
Что это?

### ISSUE THREAD

**Issue by Serhioromano** [sunengine/SunEngine#49]
Извини что пишу тут. Я просто просматривал примеры на квазаре, полазил по твоему сайту и так и не понял что это? Это что то типа CMS? Что за солнечный движек?

**Comment by DmitrijOkeanij** [comment]
Это движок для сайтов с возможностями блога, статей и форума.
Это больше чем CMS, так как имеет более широкую функциональность.

**Comment by Serhioromano** [comment]
По ссылке написаны возможности но не что это такое. Это все равно я скажу тебе что у этого есть ноги, можно ходить, бегать, есть когти и шерсть. Это ни как ни о чем не говорит. Может быть тысяча вариантов.

Нужно добавить описание 

СанЕнджин - это легкий, быстрый движек для создания сайтов основанный на современных технологиях.

**Comment by DmitrijOkeanij** [comment]
Большое спасибо!
Думаю так людям станет более ясно и понятно.

**Comment by DmitrijOkeanij** [comment]
Поменял на сайте и в README,md

**Comment by Serhioromano** [comment]
Нужно обязательно упомянуть, что пользователь сможет быстро, сгенерировать приложения своего сайта под все платформы. Это ключевая фича, о ней ни где ни слова.

**Comment by DmitrijOkeanij** [comment]
Это пока только теоретическая возможность, которая обеспечивается Квазаром, но не проверялась на практике. Сейчас на это нет времени. Я думаю что придёт время и кто захочет это себе, тогда я доделаю, если там что-тоинадо будет доделывать и заявим что это можно.
